### ISSUE TITLE
Offset for different OLEDs

### ISSUE THREAD

**Issue by DuyTrandeLion** [afiskon/stm32-ssd1306#25] opened 2020-03-25 10:43 UTC
Dear afiskon,

I discovered that some displays will have offset in x or y axis. Sometimes the text is shifted left/right or up/down several pixels. I found the solution for this is simple.
In **ssd1306.h**
``` C lang
/* SSD1309 offset of x in pixels  */
#ifndef SSD1309_OFFSET_X
#define SSD1309_OFFSET_X        -2
#endif

/* SSD1309 offset of y in pixels  */
#ifndef SSD1309_OFFSET_Y
#define SSD1309_OFFSET_Y        0
#endif
```
In **ssd1306.c**
``` C lang
void ssd1306_SetCursor(uint8_t x, uint8_t y) {
    SSD1306.CurrentX = x - SSD1309_OFFSET_X ;
    SSD1306.CurrentY = y - SSD1309_OFFSET_Y;
}
```

**Comment by afiskon** [comment] 2021-01-16 12:33
I believe this is a duplicate of https://github.com/afiskon/stm32-ssd1306/issues/36 and the proposed approach has a similar issue with out-of-buffer reading. Please see the discussion in #36. A few extra comments where added to ssd1306_conf.h to make it more clear what to do in this situation.

Please let me know if it worked out OK for your display.

**Closed by afiskon** 2021-01-16 12:33 UTC
